### ISSUE TITLE
authkit-js refresh token requests 400

### ISSUE THREAD

**Issue by paulfalgout** [workos/authkit-js#37] opened 2024-10-18 05:12 UTC
From the timeout
https://github.com/workos/authkit-js/blob/cdef77b7c38479897d7ebc7e446c7d47dc69d9a4/src/create-client.ts#L159

<img width="635" alt="Screenshot 2024-10-18 at 2 07 13 PM" src="https://github.com/user-attachments/assets/796aa090-faa0-40e7-9a94-ad830e5a86c5">

**Comment by cmatheson** [comment] 2024-10-18 15:26
hey @paulfalgout , could you give a bit more context? (how to reproduce, what type of environment, etc.).

**Comment by geoffsoftledger** [comment] 2024-10-18 19:50
Having this same issue... Looks like this only happens when devMode={false}

**Comment by southgate** [comment] 2024-10-18 20:43
@paulfalgout we need to do a better job with that error.  

For security reasons, we rely on passing the refresh token in an http only cookie to the WorkOS API in production.

What’s likely happening is that you haven’t yet set up a [custom domain](https://workos.com/docs/custom-domains/auth-api), so some browsers are blocking your WorkOS session cookie as a 3rd party cookie (this is the reason we use the localstorage in development — we want to avoid that 3rd party cookie blocking).

**Comment by paulfalgout** [comment] 2024-10-21 12:05
And then modify `apiHostname` in the `createClientOptions` like `await createClient(clientId, { apiHostname: authenticationapi.com });` ?

**Comment by dhiraj-shipmnts** [comment] 2024-11-14 17:17
Facing the same issue in testing environments when devMode is false. Look at this snap, the refresh token goes empty in the api request.
<img width="682" alt="Screenshot 2024-11-14 at 10 46 48 PM" src="https://github.com/user-attachments/assets/6e7d24b7-58cb-47e7-a4d8-94249177f71f">

I have not setup custom domain for my environment but I have allowed 3rd party cookies for api.workos.com. Can you provide any solution for this @cmatheson @southgate 

<img width="682" alt="Screenshot 2024-11-14 at 10 43 18 PM" src="https://github.com/user-attachments/assets/53866d58-8ef5-424c-9872-2280a39b8cf5">

**Comment by geoffsoftledger** [comment] 2024-11-14 18:00
Confirming this is still an issue even when setting a custom domain for us. 

I received the response below on 10/21:

```
There’s an issue at the intersection of session cookies, custom domains, and staging environments that means the session cookie doesn’t get set.

The fix for this is likely some weeks out. If you run this in a Production environment, though, it should behave as expected.
```

**Comment by burnto** [comment] 2024-11-27 00:22
Seeing this also. It's an issue on production that we don't see in development. Going to try older versions.

**Comment by cmatheson** [comment] 2024-11-28 00:54
hey everyone, i'm going to close this issue, but i wanted to clarify what is happening and what is expected:

* It is more secure to use the session cookie instead of a refresh token in localStorage. For this reason, we depend on a cookie being set when `devMode={false}`.
* The session cookie is only set when a custom domain is enabled. Additionally, you should specify the custom host domain in AuthKitProvider (`<AuthKitProvider apiHostname={auth.foo-corp.com} />`)
* Because we don't currently offer custom domains for our staging environments, you should use `devMode={true}` when developing against your staging environment (this is automatically set when you're developing locally).

**Closed by cmatheson** 2024-11-28 00:54 UTC
